import './index.scss'

export * from './common/utils/basex'
export * from './common/utils/datetime'
export * from './common/utils/media'
export * from './common/utils/mime'
export * from './common/utils/pagination'
export * from './common/utils/rand'
export * from './common/utils/string'
export * from './common/utils/uri'
export * from './common/utils/html'
export * from './common/utils/email'
export * from './common/utils/uuid'
export * from './index.common'
export * from './client/postoffice/mailbox'
export * from './client/clipboard'
export * from './common/models/toc'
export * from './common/models/stele'
export * from './common/parser/markdown'
export * from './common/parser/view'
export * from './client/editor/editor'
export * from './client/editor/nodes/node'
export * from './client/editor/nodes/codeblock'
export * from './client/editor/nodes/header'
export * from './client/editor/nodes/paragraph'
export * from './client/editor/nodes/quote-block'
export * from './client/editor/nodes/text'
export * from './client/article'
export * from './server/article'

export function sayHelloCommon(word: string) {
    return "Hello from Common!" + word
}
